name: Build Documentation
on: [ push ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: install requirements
        run: pip install --requirement=requirements.txt
    
      - name: make html documentation
        run: |
          mkdocs build
          touch site/.nojekyll
          
      - name: deploy to github pages
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
          CLEAN: true